### ISSUE TITLE
Issue with SpongeForge 1.12

### ISSUE THREAD

**Issue by JoeSGT** [thiakil/GottaGoFast#1]
https://pastebin.com/7DnPrbAd
i just added the mod with Spongeforge and it crash can you please fix this?
thanks
SpongeForge - 1.12.2-2529-7.0.0-BETA-2732
Forge - 1.12.2-14.23.0.2541-universal

**Comment by thiakil** [comment]
This is probably their issue, as I don't know how their classloading works, and as far as I'm aware the classes loaded during the rewrite should be running through the normal CoreMod pipeline.

If they can show me where I'm going wrong though and it's non-disruptive I can fix it.

**Comment by JoeSGT** [comment]
nvm about this sponge just release an option to change the player/entity moved wrongly!
enable us to control it

**Comment by Dockter** [comment]
Regardless they are doing classloading wrong.  Why are they loading this class so early: net.minecraft.util.text.TextComponentBase ?

**Comment by thiakil** [comment]
I think it's complaining that my mod is loading it early (as a side effect of rewriting the `NetHandlerPlayServer` class) or it's loaded before they do whatever it is that they do to it

It also seems to be removing transformers from the list?!
