### ISSUE TITLE
Crashing from various movements

### ISSUE THREAD

**Issue by Nick-Jus** [thiakil/GottaGoFast#5]
My entire game has crashed a few times from things like flying quickly, riding a boat, or teleporting with Waystones or /home and similar commands. Whichever method it is, it is always the same crash.

https://pastebin.com/9BWpmj84

I want to believe that it is something to do with being in the air (Flying) while attempting to teleport. The game crashes upon reaching the location, not the act of teleporting, but the location remains unloaded before crashing a second later.

Forge Version 14.23.5.2838
GottaGoFast Version 1.1
Multiplayer Server, Serverside Only

**Comment by twipsta** [comment]
Sorry to jump in but I was researching this mod to help with an issue I'm facing with another mod.
I have received almost the exact same error when leaving my base on a FTB Interactions server without this mod.

If you look near the top of the stack trace it references Spectre Coils from randomthings, and p455w0rd lib:
    at lumien.randomthings.tileentity.TileEntitySpectreCoil.hasCapability(TileEntitySpectreCoil.java:65)
    at p455w0rdslib.capabilities.CapabilityLightEmitter.hasCap(CapabilityLightEmitter.java:47)

Basically, from what I can figure out it's the spectre coils from random things and the dynamic lighting from p455w0rd lib not playing nice together, as can be seen here: [https://github.com/lumien231/Random-Things/issues/417](https://github.com/lumien231/Random-Things/issues/417)
The issue report is actually in regards to another dynamic lighting mod but near the bottom there are also reports from FTB Interactions and All The Mods which both use p455w0rd lib

I think both random things and p455w0rd lib has been updated to hopefully fix this issue but if this is for a mod pack server things can get messy.

Hope any of this helps!
